# Generated by Django 3.0.4 on 2020-03-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitchen2Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('email', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='kitchens/')),
                ('description', models.TextField(blank=True)),
                ('workingDays', models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('Th', 'Thursday'), ('F', 'Friday')], default='M', max_length=2)),
            ],
        ),
    ]
