# Generated by Django 3.0.4 on 2020-03-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=200)),
                ('veg', models.BooleanField(default=False)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, default='', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Kitchen2Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('email', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='kitchens/')),
                ('description', models.TextField(blank=True)),
                ('monday', models.BooleanField(default=False)),
                ('mondayStartTime', models.CharField(choices=[('Tm1', '8:00'), ('Tm2', '8:30'), ('Tm3', '9:00'), ('Tm4', '9:30'), ('Tm5', '10:00'), ('Tm6', '10:30'), ('Tm7', '11:00'), ('Tm8', '11:30'), ('Tm9', '12:00'), ('Tm10', '12:30'), ('Tm11', '13:00'), ('Tm12', '13:30'), ('Tm13', '14:00'), ('Tm14', '14:30'), ('Tm15', '15:00'), ('Tm16', '15:30'), ('Tm17', '16:00'), ('Tm18', '16:30'), ('Tm19', '17:00')], default='Tm1', max_length=4)),
                ('mondayEndTime', models.CharField(choices=[('Tm1', '8:00'), ('Tm2', '8:30'), ('Tm3', '9:00'), ('Tm4', '9:30'), ('Tm5', '10:00'), ('Tm6', '10:30'), ('Tm7', '11:00'), ('Tm8', '11:30'), ('Tm9', '12:00'), ('Tm10', '12:30'), ('Tm11', '13:00'), ('Tm12', '13:30'), ('Tm13', '14:00'), ('Tm14', '14:30'), ('Tm15', '15:00'), ('Tm16', '15:30'), ('Tm17', '16:00'), ('Tm18', '16:30'), ('Tm19', '17:00')], default='Tm19', max_length=4)),
                ('tuesday', models.BooleanField(default=False)),
                ('tuesdayStartTime', models.CharField(choices=[('Tm1', '8:00'), ('Tm2', '8:30'), ('Tm3', '9:00'), ('Tm4', '9:30'), ('Tm5', '10:00'), ('Tm6', '10:30'), ('Tm7', '11:00'), ('Tm8', '11:30'), ('Tm9', '12:00'), ('Tm10', '12:30'), ('Tm11', '13:00'), ('Tm12', '13:30'), ('Tm13', '14:00'), ('Tm14', '14:30'), ('Tm15', '15:00'), ('Tm16', '15:30'), ('Tm17', '16:00'), ('Tm18', '16:30'), ('Tm19', '17:00')], default='Tm1', max_length=4)),
                ('tuesdayEndTime', models.CharField(choices=[('Tm1', '8:00'), ('Tm2', '8:30'), ('Tm3', '9:00'), ('Tm4', '9:30'), ('Tm5', '10:00'), ('Tm6', '10:30'), ('Tm7', '11:00'), ('Tm8', '11:30'), ('Tm9', '12:00'), ('Tm10', '12:30'), ('Tm11', '13:00'), ('Tm12', '13:30'), ('Tm13', '14:00'), ('Tm14', '14:30'), ('Tm15', '15:00'), ('Tm16', '15:30'), ('Tm17', '16:00'), ('Tm18', '16:30'), ('Tm19', '17:00')], default='Tm19', max_length=4)),
                ('wednesday', models.BooleanField(default=False)),
                ('wednesdayStartTime', models.CharField(choices=[('Tm1', '8:00'), ('Tm2', '8:30'), ('Tm3', '9:00'), ('Tm4', '9:30'), ('Tm5', '10:00'), ('Tm6', '10:30'), ('Tm7', '11:00'), ('Tm8', '11:30'), ('Tm9', '12:00'), ('Tm10', '12:30'), ('Tm11', '13:00'), ('Tm12', '13:30'), ('Tm13', '14:00'), ('Tm14', '14:30'), ('Tm15', '15:00'), ('Tm16', '15:30'), ('Tm17', '16:00'), ('Tm18', '16:30'), ('Tm19', '17:00')], default='Tm1', max_length=4)),
                ('wednesdayEndTime', models.CharField(choices=[('Tm1', '8:00'), ('Tm2', '8:30'), ('Tm3', '9:00'), ('Tm4', '9:30'), ('Tm5', '10:00'), ('Tm6', '10:30'), ('Tm7', '11:00'), ('Tm8', '11:30'), ('Tm9', '12:00'), ('Tm10', '12:30'), ('Tm11', '13:00'), ('Tm12', '13:30'), ('Tm13', '14:00'), ('Tm14', '14:30'), ('Tm15', '15:00'), ('Tm16', '15:30'), ('Tm17', '16:00'), ('Tm18', '16:30'), ('Tm19', '17:00')], default='Tm19', max_length=4)),
                ('thursday', models.BooleanField(default=False)),
                ('thursdayStartTime', models.CharField(choices=[('Tm1', '8:00'), ('Tm2', '8:30'), ('Tm3', '9:00'), ('Tm4', '9:30'), ('Tm5', '10:00'), ('Tm6', '10:30'), ('Tm7', '11:00'), ('Tm8', '11:30'), ('Tm9', '12:00'), ('Tm10', '12:30'), ('Tm11', '13:00'), ('Tm12', '13:30'), ('Tm13', '14:00'), ('Tm14', '14:30'), ('Tm15', '15:00'), ('Tm16', '15:30'), ('Tm17', '16:00'), ('Tm18', '16:30'), ('Tm19', '17:00')], default='Tm1', max_length=4)),
                ('thursdayEndTime', models.CharField(choices=[('Tm1', '8:00'), ('Tm2', '8:30'), ('Tm3', '9:00'), ('Tm4', '9:30'), ('Tm5', '10:00'), ('Tm6', '10:30'), ('Tm7', '11:00'), ('Tm8', '11:30'), ('Tm9', '12:00'), ('Tm10', '12:30'), ('Tm11', '13:00'), ('Tm12', '13:30'), ('Tm13', '14:00'), ('Tm14', '14:30'), ('Tm15', '15:00'), ('Tm16', '15:30'), ('Tm17', '16:00'), ('Tm18', '16:30'), ('Tm19', '17:00')], default='Tm19', max_length=4)),
                ('friday', models.BooleanField(default=False)),
                ('fridayStartTime', models.CharField(choices=[('Tm1', '8:00'), ('Tm2', '8:30'), ('Tm3', '9:00'), ('Tm4', '9:30'), ('Tm5', '10:00'), ('Tm6', '10:30'), ('Tm7', '11:00'), ('Tm8', '11:30'), ('Tm9', '12:00'), ('Tm10', '12:30'), ('Tm11', '13:00'), ('Tm12', '13:30'), ('Tm13', '14:00'), ('Tm14', '14:30'), ('Tm15', '15:00'), ('Tm16', '15:30'), ('Tm17', '16:00'), ('Tm18', '16:30'), ('Tm19', '17:00')], default='Tm1', max_length=4)),
                ('fridayEndTime', models.CharField(choices=[('Tm1', '8:00'), ('Tm2', '8:30'), ('Tm3', '9:00'), ('Tm4', '9:30'), ('Tm5', '10:00'), ('Tm6', '10:30'), ('Tm7', '11:00'), ('Tm8', '11:30'), ('Tm9', '12:00'), ('Tm10', '12:30'), ('Tm11', '13:00'), ('Tm12', '13:30'), ('Tm13', '14:00'), ('Tm14', '14:30'), ('Tm15', '15:00'), ('Tm16', '15:30'), ('Tm17', '16:00'), ('Tm18', '16:30'), ('Tm19', '17:00')], default='Tm19', max_length=4)),
                ('saturday', models.BooleanField(default=False)),
                ('saturdayStartTime', models.CharField(choices=[('Tm1', '8:00'), ('Tm2', '8:30'), ('Tm3', '9:00'), ('Tm4', '9:30'), ('Tm5', '10:00'), ('Tm6', '10:30'), ('Tm7', '11:00'), ('Tm8', '11:30'), ('Tm9', '12:00'), ('Tm10', '12:30'), ('Tm11', '13:00'), ('Tm12', '13:30'), ('Tm13', '14:00'), ('Tm14', '14:30'), ('Tm15', '15:00'), ('Tm16', '15:30'), ('Tm17', '16:00'), ('Tm18', '16:30'), ('Tm19', '17:00')], default='Tm1', max_length=4)),
                ('saturdayEndTime', models.CharField(choices=[('Tm1', '8:00'), ('Tm2', '8:30'), ('Tm3', '9:00'), ('Tm4', '9:30'), ('Tm5', '10:00'), ('Tm6', '10:30'), ('Tm7', '11:00'), ('Tm8', '11:30'), ('Tm9', '12:00'), ('Tm10', '12:30'), ('Tm11', '13:00'), ('Tm12', '13:30'), ('Tm13', '14:00'), ('Tm14', '14:30'), ('Tm15', '15:00'), ('Tm16', '15:30'), ('Tm17', '16:00'), ('Tm18', '16:30'), ('Tm19', '17:00')], default='Tm19', max_length=4)),
                ('sunday', models.BooleanField(default=False)),
                ('sundayStartTime', models.CharField(choices=[('Tm1', '8:00'), ('Tm2', '8:30'), ('Tm3', '9:00'), ('Tm4', '9:30'), ('Tm5', '10:00'), ('Tm6', '10:30'), ('Tm7', '11:00'), ('Tm8', '11:30'), ('Tm9', '12:00'), ('Tm10', '12:30'), ('Tm11', '13:00'), ('Tm12', '13:30'), ('Tm13', '14:00'), ('Tm14', '14:30'), ('Tm15', '15:00'), ('Tm16', '15:30'), ('Tm17', '16:00'), ('Tm18', '16:30'), ('Tm19', '17:00')], default='Tm1', max_length=4)),
                ('sundayEndTime', models.CharField(choices=[('Tm1', '8:00'), ('Tm2', '8:30'), ('Tm3', '9:00'), ('Tm4', '9:30'), ('Tm5', '10:00'), ('Tm6', '10:30'), ('Tm7', '11:00'), ('Tm8', '11:30'), ('Tm9', '12:00'), ('Tm10', '12:30'), ('Tm11', '13:00'), ('Tm12', '13:30'), ('Tm13', '14:00'), ('Tm14', '14:30'), ('Tm15', '15:00'), ('Tm16', '15:30'), ('Tm17', '16:00'), ('Tm18', '16:30'), ('Tm19', '17:00')], default='Tm19', max_length=4)),
                ('menu', models.ManyToManyField(to='serviceProviderApp.menuItem')),
            ],
        ),
    ]
