# Generated by Django 3.0.4 on 2020-03-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProviderApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen2register',
            name='workingDays',
        ),
        migrations.AddField(
            model_name='kitchen2register',
            name='endTime',
            field=models.CharField(choices=[('Tm1', '8:00'), ('Tm2', '8:30'), ('Tm3', '9:00'), ('Tm4', '9:30'), ('Tm5', '10:00'), ('Tm6', '10:30'), ('Tm7', '11:00'), ('Tm8', '11:30'), ('Tm9', '12:00'), ('Tm10', '12:30'), ('Tm11', '13:00'), ('Tm12', '13:30'), ('Tm13', '14:00'), ('Tm14', '14:30'), ('Tm15', '15:00'), ('Tm16', '15:30'), ('Tm17', '16:00'), ('Tm18', '16:30'), ('Tm19', '17:00')], default='Tm19', max_length=4),
        ),
        migrations.AddField(
            model_name='kitchen2register',
            name='friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kitchen2register',
            name='monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kitchen2register',
            name='saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kitchen2register',
            name='startTime',
            field=models.CharField(choices=[('Tm1', '8:00'), ('Tm2', '8:30'), ('Tm3', '9:00'), ('Tm4', '9:30'), ('Tm5', '10:00'), ('Tm6', '10:30'), ('Tm7', '11:00'), ('Tm8', '11:30'), ('Tm9', '12:00'), ('Tm10', '12:30'), ('Tm11', '13:00'), ('Tm12', '13:30'), ('Tm13', '14:00'), ('Tm14', '14:30'), ('Tm15', '15:00'), ('Tm16', '15:30'), ('Tm17', '16:00'), ('Tm18', '16:30'), ('Tm19', '17:00')], default='Tm1', max_length=4),
        ),
        migrations.AddField(
            model_name='kitchen2register',
            name='sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kitchen2register',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kitchen2register',
            name='tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kitchen2register',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
    ]
