# Generated by Django 3.0.4 on 2020-03-26 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serviceProviderApp', '0002_kitchen2register_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen2register',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
