# Generated by Django 3.0.4 on 2020-03-22 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProviderApp', '0004_auto_20200322_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen2register',
            name='menu',
        ),
        migrations.AddField(
            model_name='kitchen2register',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceProviderApp.menuItem'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, default='', max_digits=10),
        ),
    ]
