# Generated by Django 3.0.4 on 2020-03-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProviderApp', '0005_auto_20200322_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen2register',
            name='menu',
        ),
        migrations.AddField(
            model_name='kitchen2register',
            name='menu',
            field=models.ManyToManyField(to='serviceProviderApp.menuItem'),
        ),
    ]
